# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push-docker-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/fissssssh/fish-tool.app:0.1.0
          context: .

  run-latest-docker-image:
    # 需要build-and-push-docker-image完成后再执行
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: stop old service
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          # must use echo command if [ -f filepath ], because if not, command will return status 1 and then workflow stop.
          script: "[ -f ~/docker/fish-tool/docker-compose.yml ] && docker-compose -f ~/docker/fish-tool/docker-compose.yml down || [ -d ~/docker/fish-tool] && rm -rf ~/docker/fish-tool || echo 'old docker-compose file do not exists.'"

      - name: copy new docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "docker-compose.yml"
          target: "~/docker/fish-tool/"

      - name: pull latest image and run new service
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: "docker-compose -f ~/docker/fish-tool/docker-compose.yml pull && docker-compose -f ~/docker/fish-tool/docker-compose.yml up -d"
